--insertion of initial data
--default password 'user' is '123456'
--default password 'admin' is '123456'
--password was generated by bcrypt online generator

INSERT INTO users (username, password)
    VALUES ('user', '{bcrypt}$2a$08$0n4vF9QAL0VxQrBx3pEFa.yXs3ccngkY9W4qD28BAZaKol6mzitdy'),
           ('admin', '{bcrypt}$2a$08$y2xc/bzhCwi.vSX.0d.z8uhl7CGgvtMyJ94N0qVPCDmBuXWscuDBa');



--insertion of initial data

INSERT INTO authorities (username, authority)
    VALUES ('user', 'ROLE_USER'),
           ('admin', 'ROLE_USER'),
           ('admin', 'ROLE_ADMIN');

